### ISSUE TITLE
Capi v0.2.0

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/capi#1077]
It has always been our intention to make Capi a smoldot-first developer experience. For v0.1.0-gamma.0, we've focused on using proxy nodes, as this is what is currently best supported, but we will be pivoting to smoldot-first for v0.1.0. This will require ongoing collaboration with @tomaka to ensure that [the new JSON RPC specification](https://github.com/paritytech/json-rpc-interface-spec) is sufficient for our needs.

```[tasklist]
### v0.2.0
- [ ] https://github.com/paritytech/capi/issues/723
- [ ] https://github.com/paritytech/capi/issues/920
- [ ] https://github.com/paritytech/capi/issues/1141
- [ ] https://github.com/paritytech/capi/issues/812
- [ ] https://github.com/paritytech/capi/issues/1015
- [ ] https://github.com/paritytech/capi/issues/811
- [ ] https://github.com/paritytech/capi/issues/635
- [ ] https://github.com/paritytech/capi/issues/929
- [ ] https://github.com/paritytech/capi/issues/977
- [ ] https://github.com/paritytech/capi/issues/922
- [ ] https://github.com/paritytech/capi/issues/660
- [ ] https://github.com/paritytech/capi/issues/623
- [ ] https://github.com/paritytech/capi/issues/520
- [ ] https://github.com/paritytech/capi/issues/593
- [ ] https://github.com/paritytech/capi/issues/571
- [ ] https://github.com/paritytech/capi/issues/519
- [ ] https://github.com/paritytech/capi/issues/932
- [ ] https://github.com/paritytech/capi/issues/654
- [ ] https://github.com/paritytech/capi/issues/565
- [ ] https://github.com/paritytech/capi/issues/567
- [ ] https://github.com/paritytech/capi/issues/559
- [ ] https://github.com/paritytech/capi/issues/556
- [ ] https://github.com/paritytech/capi/issues/534
- [ ] https://github.com/paritytech/capi/issues/323
- [ ] https://github.com/paritytech/capi/issues/319
- [ ] https://github.com/paritytech/capi/issues/47
- [ ] https://github.com/paritytech/capi/issues/1152
- [ ] https://github.com/paritytech/capi/issues/1077
```

**Comment by tomaka** [comment]
I would suggest to address any question or problem that you might face by opening issues or discussions in the spec repo (https://github.com/paritytech/json-rpc-interface-spec/).
